### ISSUE TITLE
publish onnxconverter package in anaconda

### ISSUE THREAD

**Issue by sephib** [microsoft/onnxconverter-common#149]
Hi,
we want to publish [hummingbird ml](https://github.com/microsoft/hummingbird/issues/314#issuecomment-707812512) to anaconda.   

Since it depends on this package we need this package to also be on anaconda.

Are you planning to publish this package on anaconda or should I do so?

**Comment by xhochy** [comment]
Doing this now for conda-forge: https://github.com/conda-forge/staged-recipes/pull/14220
