### ISSUE TITLE
Fp32 to Fp16 conversion failure for CSNet

### ISSUE THREAD

**Issue by pmbrown1055** [microsoft/onnxconverter-common#171]
Steps:
1. Converted this pytorch model to ONNX FP32 (https://github.com/MCG-NKU/SOD100K/tree/master/CSNet)
2. Tried to convert the FP32 ONNX model to FP16 using the latest available onnxmltools through python pip, the output model has a strange const tree, and the output of the model is disconnected from the main model tree, making it un-executable in ORT or WinML.

**Comment by xiaowuhu** [comment]
@pmbrown1055 this issue still exist? if not, we will close this issue.

**Comment by xiaowuhu** [comment]
if this still bother you, you can reopen it.
