### ISSUE TITLE
fp32 to fp16

### ISSUE THREAD

**Issue by baheytharwat** [microsoft/onnxconverter-common#195]
I have a .onnx file for a pre-trained model and I am trying to convert it from fp32 to fp16, I used these lines of code to do this thing:
```
from onnxmltools.utils.float16_converter import convert_float_to_float16
from onnxmltools.utils import load_model, save_model

onnx_model = load_model('model.onnx')
new_onnx_model = convert_float_to_float16(onnx_model)
save_model(new_onnx_model, 'new_model.onnx')
```
but it seems the convolution kernels still have fp32 weights, How can I convert all the parameters from fp32 to fp16?

**Comment by xiaowuhu** [comment]
@baheytharwat is this issue still bother you? I cannot repro your issue. from my test case, the Weight/Bias of Conv operator are all converted to fp16.

**Comment by xiaowuhu** [comment]
if this still bother you, you can reopen it.
