### ISSUE TITLE
F16 file does not convert correctly

### ISSUE THREAD

**Issue by hardik124** [microsoft/onnxconverter-common#207]
The float16.py conversion has a blacklist option , but it does not seem to blacklist correctly and still tries to run Resize at float16, leading to errors.

**Comment by toothache** [comment]
For `Resize`, the optional inputs (e.g., `scales` and `sizes`) doesn't support fp16 and should not be converted.

I have a dirty hack to skip it.
https://github.com/toothache/onnxconverter-common/commit/596f845ff883f1a2e722acab0e7d404cc327174a

**Comment by bxing-groq** [comment]
If we submit a patch on this, how soon do we think we can get this landed in a new release?

**Comment by xiaowuhu** [comment]
fixed
