### ISSUE TITLE
Issues when converting model to float16

### ISSUE THREAD

**Issue by toothache** [microsoft/onnxconverter-common#208]
Some issues observed when converting model to float16:
- When converting model with `keep_io_types` set to `True`, `onnx.checker` will complain:
   ```
   onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted,
   ```
   The fix would be fairly simple, inserting the `Cast` operator for input tensors to the beginning of node list.
- Some operators (e.g., Resize, CumSum) support float16, however it's listed in `DEFAULT_OP_BLOCK_LIST`:
   - Should we update this list or auto generated from onnx opschema?
   - For operator like `Resize`, some of the optional inputs doesn't support float16. We need exclude fp16 conversion to them.

**Comment by xiaowuhu** [comment]
@toothache does this issue still existed?

**Comment by 1615070057** [comment]
Hi, I also encountered the same problem, The fix would be fairly simple, inserting the Cast operator for input tensors to the beginning of node list. How should I do it, thanks!

**Comment by 1615070057** [comment]
onnx.checker验证成功，但是onnxruntime加载模型报错：onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from model_fp16.onnx failed:This is an invalid model。类型错误：节点 (Resize__139) 中运算符 (Resize) 的输入参数 (const_empty_float__132) 的类型“tensor(float16 )”无效。
