### ISSUE TITLE
Add bounds warning to FP16 conversion script

### ISSUE THREAD

**Issue by kevinch-nv** [microsoft/onnxconverter-common#211]
There should be a warning thrown when FP32 values outside of FP16 representative range are clamped when converted to FP16 to notify the user of potential unwanted behavior.

Currently the conversion function silently clamps the values.

https://github.com/microsoft/onnxconverter-common/blob/fc2a187db8d6a47acac57953b765eb357caa4a5b/onnxconverter_common/float16.py

**Comment by xiaowuhu** [comment]
add warning message in PR: https://github.com/microsoft/onnxconverter-common/pull/246
