### ISSUE TITLE
Security Development Lifecycle review for 2022-06

### ISSUE THREAD

**Issue by garymm** [microsoft/onnxconverter-common#213]
The security & compliance system is called 1CS.  We are preparing a 1CS review. A major part of it is called “Security Development Lifecycle (SDL)”. You can find the SDL requirements at: https://msdata.visualstudio.com/DefaultCollection/Vienna/_compliance/product/3db74f93-ab79-972f-848a-2f402f2497cf/assessments/068b5efe-fd00-52cc-bef4-5676de0a4782 . Now we ask you please open the link, click each work item, carefully read the description. On the top of each description, you will see text like:

           [ ] microsoft/onnxruntime-extensions
           [ ] microsoft/onnxconverter-common
           [ ] microsoft/OLive
           [ ] microsoft/onnxruntime

When the work item is finished for your repo, or if you think it doesn’t apply to you, mark it as done by entering an `x` in the brackets. If you have any questions or need help, please let @snnn know. The goal is to finish all of them by 6/30. If you need more time, please let us know ahead and put a comment there with your ETA.  Before you start, please also read the FAQ part of [Software Testing and SDL | Executive Order Requirements](https://eng.ms/docs/initiatives/executive-order/executive-order-requirements/executiveorderoncybersecurity/softwaretestingsdl).

**Comment by xiaowuhu** [comment]
@garymm yes, will do.
