### ISSUE TITLE
1.12.2 version released？

### ISSUE THREAD

**Issue by philipwan** [microsoft/onnxconverter-common#245]
Hi:
I can install 1.12.2 version by
 **pip install onnxconverter-common==1.12.2**
But I note that on the home page I can only see the release information of version 1.9.0， 
I cannot found any tags/branch information about 1.12.2 except commit.
I am curious about the **release process** of  onnxconverter-coommon 
And I relly want to known  compared to the 1.9 version. what is **eleases note** of 1.12.2

Thank You!

**Comment by xiaowuhu** [comment]
https://github.com/microsoft/onnxconverter-common/releases/tag/v1.13.0 released
