### ISSUE TITLE
How to convert a model to mixed precision?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [microsoft/onnxconverter-common#252]
Hey guys,

I hope you are doing great. I am trying to convert a model to mixed precision, unfortunately, the doc is wrong and there is no clear instruction or working code that I can use.

[The doc just doesn't work](https://natke.github.io/onnxruntime/docs/performance/float16.html) see #251 

I've also tried `onnxconverter_common.auto_mixed_precision_model_path.auto_convert_mixed_precision_model_path` not even sure what changes compared to `onnxconverter_common.auto_mixed_precision.auto_convert_mixed_precision` but it doesn't work. 

**It took more than `15m` on a quite powerful machine**, this seems very odd since PyTorch takes like a fraction of a second, may I ask you what is going on internally?

It outputs a lot of garbage, sees a [txt file](https://drive.google.com/file/d/1gqAR1nT53_Iu-hPodbUSnCW6l-O0hAa2/view?usp=share_link) with the logs and doesn't perform the conversion. It's more than 100MB because the code outputs a ton of weird stuff. After a while, it crashed with just too many outputs.

I am just trying to convert a model to mixed precision, this seems like a fairly common task. *(*Could you guys invest a little bit of time in testing and writing doc**? This would help the community enormously, otherwise, most people will never be able to use the software in the current undocumented/broken state. 

I am working on an article about exporting a torch model to onnx in mixed precision. My code

```python
import onnxruntime as ort
import torch
from torchvision.models import ConvNeXt_Small_Weights, convnext_small
from onnxconverter_common.auto_mixed_precision_model_path import (
    auto_convert_mixed_precision_model_path,
)
import onnx

model_name = "model.onnx"
model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().cuda()

x = torch.randn(1, 3, 224, 224, device="cuda")
# Export the model
torch.onnx.export(
    model,  # model being run
    x,  # model input (or a tuple for multiple inputs)
    model_name,  # where to save the model (can be a file or file-like object)
    opset_version=16,
    export_params=True,  # store the trained parameter weights inside the model file
    do_constant_folding=True,  # whether to execute constant folding for optimization
    input_names=["image"],  # the model's input names
    output_names=["output"],  # the model's output names
    dynamic_axes={
        "image": {0: "batch_size"},  # variable length axes
        "output": {0: "batch_size"},
    },
)

# model = onnx.load("model.onnx")
# model_fp16 = auto_convert_mixed_precision(model, { "image" : x.cpu().numpy() }, None, rtol=0.01, atol=0.001, keep_io_types=True)
auto_convert_mixed_precision_model_path("./model.onnx", { "image" : x.cpu().numpy() }, "./model_fp16.onnx", provider=["CUDAExecutionProvider"], rtol=0.01, atol=0.001, keep_io_types=True, verbose=False)
# onnx.save(model_fp16, "model_fp16.onnx")
# let's check
print("Checking")
x = torch.randn(1, 3, 224, 224, device="cuda", dtype=torch.float16)
ort_session = ort.InferenceSession("model_fp16.onnx", providers=["CUDAExecutionProvider"])
outputs = ort_session.run(None, {"image": x.cpu().numpy()})
print(outputs[0].shape, outputs[0].dtype)
```

Thanks

**Comment by abock** [comment]
@xiaowuhu would you mind taking a look at this issue?

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks a lot :pray: Where is the correct place for me to receive support? So far only the TensorRT devs suggested me to use ONNX to convert to fp16 (following the doc) but I've encountered many issues and I was wondering where is the right place for me to continue the discussion. Pasting below issues with fp16, even if they are not completely related to mixed precision. The broad question is

**How to convert a model to fp16 and/or mixed precision**


ONNX and Torch fp16 do not give the same result

```python
def export_fp16_model():
    model_name = "model.fp16.onnx"
    model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().cuda()
    x = torch.randn(1, 3, 224, 224, device="cuda")
    export_onnx(model, x, model_name)
    # let's store the outputs to compare the results
    with torch.no_grad():
        out_torch = model.half()(x.half())
    # load fp32 model, convert to fp16
    model = onnx.load("model.onnx")
    model_fp16 = float16.convert_float_to_float16(model)
    onnx.save(model_fp16, model_name)
    ort_session = ort.InferenceSession(model_name, providers=["CUDAExecutionProvider"])
    outputs = ort_session.run(None, {"image": x.half().cpu().numpy()})
    # checking the difference
    print(np.abs(out_torch.cpu().numpy() - outputs[0]).mean())
  ```
  Prints `0.0239` 
  
  Same thing if I convert the model first in pytorch  
  
  ```python
  def export_fp16_from_torch_model():
    model_name = "model.fp16.onnx"
    model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().cuda().half()
    x = torch.randn(1, 3, 224, 224, device="cuda").half()
    export_onnx(model, x, model_name)
    # let's store the outputs to compare the results
    with torch.no_grad():
        out_torch = model(x)
    # load fp16 model
    ort_session = ort.InferenceSession(model_name, providers=["CUDAExecutionProvider"])
    outputs = ort_session.run(None, {"image": x.half().cpu().numpy()})
    # checking the difference
    print(np.abs(out_torch.cpu().numpy() - outputs[0]).mean())
    ``` 

Prints `0.0239`

**Comment by FrancescoSaverioZuppichini** [comment]
guys?

**Comment by xiaowuhu** [comment]
Sure.  just come back from long CNY vacation. will look into it soon.

**Comment by FrancescoSaverioZuppichini** [comment]
@xiaowuhu Hope to had a great time :)

**Comment by xiaowuhu** [comment]
@FrancescoSaverioZuppichini 

can you please try below API call:

```python
def convert_float32_to_float16(fp32_model_path, fp16_model_path):
    from onnxmltools.utils.float16_converter import convert_float_to_float16
    from onnxmltools.utils import save_model

    model = onnx.load(fp32_model_path)
    new_onnx_model = convert_float_to_float16(model, keep_io_types=True)
    save_model(new_onnx_model, fp16_model_path)

convert_float32_to_float16("fp32.onnx", "fp16_1.onnx")
```

if still not work, you could share me your onnx model in Google drive (if the model is very large), or just send me email (xiaowuhu@microsoft.com) and attached it (if it is smaller than 200M).

**Comment by NarutoUA** [comment]
@xiaowuhu

Hi, I have the same issue as posted above. **convert_float32_to_float16** function works, model is converted successfuly (it can be loaded by onnx runtime (1.13.1) and nodes looks converted in Netron view). However, it fails on inference with error:

`[E:onnxruntime:, sequential_executor.cc:369 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Conv node. Name:'Conv_1221' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\op_kernel.cc:81 onnxruntime::OpKernelContext::OutputMLValue status.IsOK() was false. Shape mismatch attempting to re-use buffer. {1,3,552,492} != {1,3,1104,984}. Validate usage of dim_value (values should be > 0) and dim_param (all values with the same string should equate to the same size) in shapes in the model.`

It fails only with CUDA/DML providers. If I use CPU it runs ok and produces valid output. {1,3,552,492} is my input shape and {1,3,1104,984} is output for super-resolution model with 2x upscale. I guess something wrong with inserting Cast operatators to converted model. I could use `keep_io_types=False` (converted model runs without errors) but .NET doesn't have built-in complete float16 type and it would be painful to convert float32 -> float16 -> float32
<details>
<summary>some Netron screenshots</summary>

![image](https://user-images.githubusercontent.com/6840502/216745896-3eb511cf-8528-44d5-b13b-83bfad623e5e.png)
![image](https://user-images.githubusercontent.com/6840502/216745921-fb344b6c-6530-4268-8427-d2ca13547fea.png)
![image](https://user-images.githubusercontent.com/6840502/216745930-7fda5f02-7a18-4730-ae2c-d7d84d0a723d.png)

</details>

**Comment by xiaowuhu** [comment]
@NarutoUA Hi, can you share to me your fp32 onnx model so I can repro?
In general, if CPU provider can work, but GPU provider failed, it should be an issue in onnxruntime-GPU code. I can only repro, but the fix should be done by onnxruntime team. You'd better open an onnxruntime github issues.

**Comment by NarutoUA** [comment]
@xiaowuhu Thanks for reply. I created new [onnxruntime issue](https://github.com/microsoft/onnxruntime/issues/14582). If you still want to reproduce a bug, there are attached models.

**Comment by xiaowuhu** [comment]
@NarutoUA Hi, I saw your github issue for the onnxruntime. If you can share your inference code (with test data), it will be great. 
btw, you are using C# to do the inference. Do you ever try Python to get the same issue?

**Comment by NarutoUA** [comment]
@xiaowuhu Hello, I've updated google drive link with python code and test data (yep, python gives me the same error)

**Comment by FrancescoSaverioZuppichini** [comment]
> @FrancescoSaverioZuppichini
> 
> can you please try below API call:
> 
> ```python
> def convert_float32_to_float16(fp32_model_path, fp16_model_path):
>     from onnxmltools.utils.float16_converter import convert_float_to_float16
>     from onnxmltools.utils import save_model
> 
>     model = onnx.load(fp32_model_path)
>     new_onnx_model = convert_float_to_float16(model, keep_io_types=True)
>     save_model(new_onnx_model, fp16_model_path)
> 
> convert_float32_to_float16("fp32.onnx", "fp16_1.onnx")
> ```
> 
> if still not work, you could share me your onnx model in Google drive (if the model is very large), or just send me email ([xiaowuhu@microsoft.com](mailto:xiaowuhu@microsoft.com)) and attached it (if it is smaller than 200M).

Will do, I'll keep you posted. Thanks a lot! You can generate the onnx model by run the code in the first issue

**Comment by FrancescoSaverioZuppichini** [comment]
@xiaowuhu the code will create a fp16 model with a very big difference in results compared to the original half torch model

```python
import numpy as np
import onnx
import onnxruntime as ort
import torch
from onnxconverter_common import float16
from onnxconverter_common.auto_mixed_precision import \
    auto_convert_mixed_precision
from torchvision.models import ConvNeXt_Small_Weights, convnext_small

torch.manual_seed(0)

def export_onnx(model, x, model_name):
    torch.onnx.export(
    model,  # model being run
    x,  # model input (or a tuple for multiple inputs)
    model_name,  # where to save the model (can be a file or file-like object)
    opset_version=16,
    export_params=True,  # store the trained parameter weights inside the model file
    do_constant_folding=True,  # whether to execute constant folding for optimization
    input_names=["image"],  # the model's input names
    output_names=["output"],  # the model's output names
    dynamic_axes={
        "image": {0: "batch_size"},  # variable length axes
        "output": {0: "batch_size"},
        },
    )

def export_fp16_model():
    from onnxmltools.utils.float16_converter import convert_float_to_float16
    model_name = "model.fp16.onnx"
    model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().cuda()
    x = torch.randn(1, 3, 224, 224, device="cuda")
    export_onnx(model, x, model_name)
    # let's store the outputs to compare the results
    with torch.no_grad():
        out_torch = model.half()(x.half())
    # load fp32 model, convert to fp16
    model = onnx.load("model.onnx")
    model_fp16 = convert_float_to_float16(model)
    onnx.save(model_fp16, model_name)
    ort_session = ort.InferenceSession(model_name, providers=["CUDAExecutionProvider"])
    outputs = ort_session.run(None, {"image": x.half().cpu().numpy()})
    # checking the difference
    print(np.abs(out_torch.cpu().numpy() - outputs[0]).mean())
    

export_fp16_model()
```

prints `0.02388`, if we convert to fp16 in torch and export

```
def export_fp16_from_torch_model():
    model_name = "model.fp16.onnx"
    model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().cuda().half()
    x = torch.randn(1, 3, 224, 224, device="cuda").half()
    export_onnx(model, x, model_name)
    # let's store the outputs to compare the results
    with torch.no_grad():
        out_torch = model.half()(x.half())
    # load fp16 model
    ort_session = ort.InferenceSession(model_name, providers=["CUDAExecutionProvider"])
    outputs = ort_session.run(None, {"image": x.half().cpu().numpy()})
    # checking the difference
    print(np.abs(out_torch.cpu().numpy() - outputs[0]).mean())

export_fp16_from_torch_model()
```

The printed number is `0.02385`, very close.

*cool, we know now how to export to fp16*

**However, now the questions: how to convert to mixed precision?**

**Comment by donrax** [comment]
You can try exporting your mixed-precision pytorch model to an onnx model by using python's context manager:

<pre lang="python">
from torch.cuda import amp

with amp.autocast(enabled=True):
    torch.onnx.export(...)
</pre>

By editing your code:
<pre lang="python">
def export_onnx(model, x, model_name):
    with amp.autocast(enabled=True):
        torch.onnx.export(
            model,  # model being run
            x,  # model input (or a tuple for multiple inputs)
            model_name,  # where to save the model (can be a file or file-like object)
            opset_version=16,
            export_params=True,  # store the trained parameter weights inside the model file
            do_constant_folding=True,  # whether to execute constant folding for optimization
            input_names=["image"],  # the model's input names
            output_names=["output"],  # the model's output names
            dynamic_axes={
                "image": {0: "batch_size"},  # variable length axes
                "output": {0: "batch_size"},
                },
            opset_version=15
        )
</pre>

**Comment by FrancescoSaverioZuppichini** [comment]
@donrax I was told by onnx people to don't use pytorch to convert it to mixed precision but use onnx

@xiaowuhu @NarutoUA any update from your side?

Thanks

Fra

**Comment by rfbr** [comment]
Hello team!
Still no update @xiaowuhu @NarutoUA ? Facing the same issue.
Thanks for your help.

**Comment by fabiozappo** [comment]
@FrancescoSaverioZuppichini 

After several tries I obtained the best results using the approach by donrax which does not involve onnxconverter. The error goes from 0.02 to 0.0007 when using amp.

```
import time
import numpy as np
import onnx
import onnxruntime as ort
import torch
from torchvision.models import ConvNeXt_Small_Weights, convnext_small

torch.manual_seed(0)

def export_amp_onnx(model, x, model_name, use_amp):
    with torch.cuda.amp.autocast(enabled=use_amp):
        torch.onnx.export(
        model,  # model being run
        x,  # model input (or a tuple for multiple inputs)
        model_name,  # where to save the model (can be a file or file-like object)
        opset_version=16,
        export_params=True,  # store the trained parameter weights inside the model file
        do_constant_folding=True,  # whether to execute constant folding for optimization
        input_names=["image"],  # the model's input names
        output_names=["output"],  # the model's output names
        dynamic_axes={
            "image": {0: "batch_size"},  # variable length axes
            "output": {0: "batch_size"},
            },
        )
    


device = "cuda"
use_amp = True

# Load Model
model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().to(device)

# Prepare input
x = torch.randn(1, 3, 224, 224).to(device)

model_name = "model.amp.onnx"

export_amp_onnx(model, x, model_name, use_amp)

# Reload the runtime 
ort_session = ort.InferenceSession(model_name, providers=["CUDAExecutionProvider"])

num_experiments = 15
for i in range(num_experiments):

    x = torch.randn(1, 3, 224, 224)
    
    # timing torch (copy of tensor between different devices included in the benchmark)
    since = time.time()
    with torch.cuda.amp.autocast(enabled=use_amp) and torch.no_grad():
        x_gpu = x.to(device)
        out_torch = model(x_gpu)
    out_torch = out_torch.cpu().numpy()
    torch_time = time.time() - since

    # timing onnx runtime
    since = time.time()
    out_onnx = ort_session.run(None, {"image": x.cpu().numpy()})
    onnx_time = time.time() - since

    # checking the difference
    error = np.abs(out_torch - out_onnx[0]).mean()

    # checking the difference
    print(f"Error: {error:.6f}, Onnx time: {onnx_time:.3f}, Torch time: {torch_time:.3f}")
```

Running the following script this is what I get.
```

============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Error: 0.000595, Onnx time: 1.657, Torch time: 0.022
Error: 0.000689, Onnx time: 0.006, Torch time: 0.013
Error: 0.000607, Onnx time: 0.005, Torch time: 0.013
Error: 0.000764, Onnx time: 0.005, Torch time: 0.013
Error: 0.000558, Onnx time: 0.005, Torch time: 0.012
Error: 0.000782, Onnx time: 0.005, Torch time: 0.014
Error: 0.000738, Onnx time: 0.005, Torch time: 0.014
Error: 0.000594, Onnx time: 0.005, Torch time: 0.013
Error: 0.000707, Onnx time: 0.005, Torch time: 0.012
Error: 0.000728, Onnx time: 0.005, Torch time: 0.012
Error: 0.000720, Onnx time: 0.005, Torch time: 0.012
Error: 0.000673, Onnx time: 0.005, Torch time: 0.012
Error: 0.000685, Onnx time: 0.005, Torch time: 0.012
Error: 0.000788, Onnx time: 0.005, Torch time: 0.013
Error: 0.000731, Onnx time: 0.005, Torch time: 0.012
```

Running the same script with `use_amp = False` i get longer inference times and smaller errors as expected.

**Comment by donrax** [comment]
Cool. Glad to hear :)

**Comment by FrancescoSaverioZuppichini** [comment]
@fabiozappo thanks a lot (be sure to use `python` keyword in your markdown file so you have syntax highliting)

**Comment by MaanavD** [comment]
Hi @FrancescoSaverioZuppichini ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary.
