### ISSUE TITLE
protobuf version

### ISSUE THREAD

**Issue by OKUA1** [microsoft/onnxconverter-common#265]
Is there a reason for protobuf version to be fixed to 3.20.2 ? I believe onnx now supports protobuf >= 4, so it would be nice if onnxconverter could be updated as well.

**Comment by xiaowuhu** [comment]
done

**Comment by ecederstrand** [comment]
Any chances this could reach a version on PyPI soon?

**Comment by adielashrov** [comment]
Hey,
I'm experiencing this issue as well.

I've attached the output of the pip freeze
[pip_freeze.txt](https://github.com/user-attachments/files/17450301/pip_freeze.txt)

Any ideas on how to overcome this?

Regards,
Adiel

**Comment by AndreyOrb** [comment]
Any chance to update the PyPi?

**Comment by AndreyOrb** [comment]
Ended up installing directly from GitHub:
`poetry add git+https://github.com/microsoft/onnxconverter-common.git`
