### ISSUE TITLE
Extra Cast nodes causes overflow in onnxruntime 1.17

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxconverter-common#271]
Some user reported that extra Cast nodes after running auto mixed precision conversion. See related issue here:
https://github.com/microsoft/onnxruntime/issues/19437

ORT 1.17 has changed the behavior of Cast node removal, and no longer remove down cast (like float32 to float16 Cast). Please fix the fp16 conversion script to avoid adding extra Cast nodes. For example,  the cast nodes in  `fp32 ---> Cast (to=fp16) --> Cast (to=fp32)--> fp32` can be removed with some post processing.

**Comment by xiaowuhu** [comment]
This PR https://github.com/microsoft/onnxconverter-common/pull/286 resolved this issue.
