### ISSUE TITLE
Test test_to_onnx_type fails in version 1.6.0

### ISSUE THREAD

**Issue by mslacken** [microsoft/onnxconverter-common#69]
One of the tests fail in version 1.6.0. Used versions are
 platform linux -- Python 3.7.3, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
The output of the failed test is:
self = <test_onnx.TestTypes testMethod=test_to_onnx_type>

     def test_to_onnx_type(self):
         dt = FloatTensorType((1, 5))
         assert str(dt) == 'FloatTensorType(shape=(1, 5))'
         onx = dt.to_onnx_type()
         assert "dim_value: 5" in str(onx)
         tt = onx.tensor_type
         assert "dim_value: 5" in str(tt)
         assert tt.elem_type == 1
>       o = onx.sequence_type
E       AttributeError: 'TypeProto' object has no attribute 'sequence_type'

**Comment by scarabeusiv** [comment]
It was caused by overlooked dependency on our openSUSE packaging, nothing for upstream to do here.
